export class QnaResExample {
  public readonly create = {
    status: 201,
    description: '새로운 Q&A 작성 완료',
    success: true,
    data: {
      id: 2,
      createdTime: '2022-07-16 02:30:00',
      content: '가격 할인 되나요?',
      reply: '네고 안됩니다.',
      space: {
        id: 26,
        type: '세미나실',
        address: '서울시 어쩌구',
        name: '좋은 세미나실',
        notice: '공지사항 어쩌구 저쩌구',
        intro: '넓고 깔끔',
        user: {
          id: 57,
          isAdmin: false,
          nickname: 'test2',
          email: 'test2@naver.com',
          password: '****',
          name: '김태훈',
          sex: null,
          profileImage: null,
          phoneNumber: null,
          businessNumber: null,
          businessName: null,
          businessAddress: null,
          accountNumber: null,
          reservations: [],
          spaces: [
            {
              id: 26,
              type: '세미나실',
              address: '서울시 어쩌구',
              name: '좋은 세미나실',
              notice: '공지사항 어쩌구 저쩌구',
              intro: '넓고 깔끔',
            },
            {
              id: 25,
              type: '스터디룸',
              address: '여기서 멀어요',
              name: '스터디룸 ㅋㅋ',
              notice: '공지사항 어쩌구 저쩌구',
              intro: '넓고 깔끔',
            },
          ],
        },
        hashtags: [],
      },
      user: {
        id: 57,
        isAdmin: false,
        nickname: 'test2',
        email: 'test2@naver.com',
        password: '****',
        name: '김태훈',
        sex: null,
        profileImage: null,
        phoneNumber: null,
        businessNumber: null,
        businessName: null,
        businessAddress: null,
        accountNumber: null,
        reservations: [],
        spaces: [
          {
            id: 25,
            type: '스터디룸',
            address: '여기서 멀어요',
            name: '스터디룸 ㅋㅋ',
            notice: '공지사항 어쩌구 저쩌구',
            intro: '넓고 깔끔',
            hashtags: [],
          },
        ],
      },
    },
  };
  public readonly findAll = {
    status: 200,
    description: '전체 Q&A 목록 조회 성공',
    success: true,
    data: [
      {
        id: 2,
        createdTime: '2022-07-16 02:30:00',
        content: '가격 할인 되나요?',
        reply: '네고 안됩니다.',
        space: {
          id: 26,
          type: '세미나실',
          address: '서울시 어쩌구',
          name: '좋은 세미나실',
          notice: '공지사항 어쩌구 저쩌구',
          intro: '넓고 깔끔',
          user: {
            id: 57,
            isAdmin: false,
            nickname: 'test2',
            email: 'test2@naver.com',
            password: '****',
            name: '김태훈',
            sex: null,
            profileImage: null,
            phoneNumber: null,
            businessNumber: null,
            businessName: null,
            businessAddress: null,
            accountNumber: null,
            reservations: [],
            spaces: [
              {
                id: 26,
                type: '세미나실',
                address: '서울시 어쩌구',
                name: '좋은 세미나실',
                notice: '공지사항 어쩌구 저쩌구',
                intro: '넓고 깔끔',
              },
              {
                id: 25,
                type: '스터디룸',
                address: '여기서 멀어요',
                name: '스터디룸 ㅋㅋ',
                notice: '공지사항 어쩌구 저쩌구',
                intro: '넓고 깔끔',
              },
            ],
          },
          hashtags: [],
        },
        user: {
          id: 57,
          isAdmin: false,
          nickname: 'test2',
          email: 'test2@naver.com',
          password: '****',
          name: '김태훈',
          sex: null,
          profileImage: null,
          phoneNumber: null,
          businessNumber: null,
          businessName: null,
          businessAddress: null,
          accountNumber: null,
          reservations: [],
          spaces: [
            {
              id: 25,
              type: '스터디룸',
              address: '여기서 멀어요',
              name: '스터디룸 ㅋㅋ',
              notice: '공지사항 어쩌구 저쩌구',
              intro: '넓고 깔끔',
              hashtags: [],
            },
          ],
        },
      },
      {
        id: 3,
        createdTime: '2022-07-16 03:30:00',
        content: '가격 할인 부탁드려요',
        reply: '네고 안됩니다.',
        space: {
          id: 26,
          type: '세미나실',
          address: '서울시 어쩌구',
          name: '좋은 세미나실',
          notice: '공지사항 어쩌구 저쩌구',
          intro: '넓고 깔끔',
          user: {
            id: 57,
            isAdmin: false,
            nickname: 'test2',
            email: 'test2@naver.com',
            password: '****',
            name: '김태훈',
            sex: null,
            profileImage: null,
            phoneNumber: null,
            businessNumber: null,
            businessName: null,
            businessAddress: null,
            accountNumber: null,
            reservations: [],
            spaces: [
              {
                id: 26,
                type: '세미나실',
                address: '서울시 어쩌구',
                name: '좋은 세미나실',
                notice: '공지사항 어쩌구 저쩌구',
                intro: '넓고 깔끔',
              },
              {
                id: 25,
                type: '스터디룸',
                address: '여기서 멀어요',
                name: '스터디룸 ㅋㅋ',
                notice: '공지사항 어쩌구 저쩌구',
                intro: '넓고 깔끔',
              },
            ],
          },
          hashtags: [],
        },
        user: {
          id: 57,
          isAdmin: false,
          nickname: 'test2',
          email: 'test2@naver.com',
          password: '****',
          name: '김태훈',
          sex: null,
          profileImage: null,
          phoneNumber: null,
          businessNumber: null,
          businessName: null,
          businessAddress: null,
          accountNumber: null,
          reservations: [],
          spaces: [
            {
              id: 25,
              type: '스터디룸',
              address: '여기서 멀어요',
              name: '스터디룸 ㅋㅋ',
              notice: '공지사항 어쩌구 저쩌구',
              intro: '넓고 깔끔',
              hashtags: [],
            },
          ],
        },
      },
    ],
  };
  public readonly findOne = {
    status: 200,
    success: true,
    description: 'qnaId로 qna 조회 성공',
    data: {
      id: 2,
      createdTime: '2022-07-16 02:30:00',
      content: '가격 할인 되나요?',
      reply: '네고 안됩니다.',
      space: {
        id: 26,
        type: '세미나실',
        address: '서울시 어쩌구',
        name: '좋은 세미나실',
        notice: '공지사항 어쩌구 저쩌구',
        intro: '넓고 깔끔',
        user: {
          id: 57,
          isAdmin: false,
          nickname: 'test2',
          email: 'test2@naver.com',
          password: '****',
          name: '김태훈',
          sex: null,
          profileImage: null,
          phoneNumber: null,
          businessNumber: null,
          businessName: null,
          businessAddress: null,
          accountNumber: null,
          reservations: [],
          spaces: [
            {
              id: 26,
              type: '세미나실',
              address: '서울시 어쩌구',
              name: '좋은 세미나실',
              notice: '공지사항 어쩌구 저쩌구',
              intro: '넓고 깔끔',
            },
            {
              id: 25,
              type: '스터디룸',
              address: '여기서 멀어요',
              name: '스터디룸 ㅋㅋ',
              notice: '공지사항 어쩌구 저쩌구',
              intro: '넓고 깔끔',
            },
          ],
        },
        hashtags: [],
      },
      user: {
        id: 57,
        isAdmin: false,
        nickname: 'test2',
        email: 'test2@naver.com',
        password: '****',
        name: '김태훈',
        sex: null,
        profileImage: null,
        phoneNumber: null,
        businessNumber: null,
        businessName: null,
        businessAddress: null,
        accountNumber: null,
        reservations: [],
        spaces: [
          {
            id: 25,
            type: '스터디룸',
            address: '여기서 멀어요',
            name: '스터디룸 ㅋㅋ',
            notice: '공지사항 어쩌구 저쩌구',
            intro: '넓고 깔끔',
            hashtags: [],
          },
        ],
      },
    },
  };
  public readonly updateQna = {
    status: 201,
    description: 'qnaId로 특정 Q&A 수정',
    success: true,
    data: { affected: true },
  };

  public readonly updateMyQna = {
    status: 201,
    description: 'qnaId로 내가 작성한 특정 Q&A 수정',
    success: true,
    data: { affected: true },
  };

  public readonly removeQna = {
    status: 201,
    description: 'qnaId로 특정 Q&A 삭제 성공',
    success: true,
  };

  public readonly removeMyQna = {
    status: 201,
    description: 'qnaId로 내가 작성한 특정 Q&A 삭제 성공',
    success: true,
  };

  public readonly findAllBySpace = {
    status: 200,
    description: '특정 공간의 Q&A 목록 조회 성공',
    success: true,
    data: {
      totalPage: 1,
      paginatedQnas: [
        {
          id: 5,
          createdTime: '2022-07-17T12:19:14.000Z',
          content: '숙박 가능한 방인가요?1',
          reply: null,
          space: {
            id: 50,
            type: '세미나실',
            address: 'ㅁㄴㅁㄴasdf',
            name: '세미나실123',
            notice: '123ㅁㄴㄴㅁ4',
            intro: 'tgdㅁㄴㄴㅁsvcax',
            user: {
              id: 74,
              isAdmin: false,
              nickname: 'ttest',
              email: 'tester@t.com',
              password: '****',
              name: null,
              sex: null,
              profileImage: null,
              phoneNumber: null,
              businessNumber: null,
              businessName: null,
              businessAddress: null,
              accountNumber: null,
            },
          },
          user: {
            id: 74,
            isAdmin: false,
            nickname: 'ttest',
            email: 'tester@t.com',
            password: '****',
            name: null,
            sex: null,
            profileImage: null,
            phoneNumber: null,
            businessNumber: null,
            businessName: null,
            businessAddress: null,
            accountNumber: null,
          },
        },
        {
          id: 5,
          createdTime: '2022-07-17T12:19:14.000Z',
          content: '숙박 가능한 방인가요?1',
          reply: null,
          space: {
            id: 50,
            type: '세미나실',
            address: 'ㅁㄴㅁㄴasdf',
            name: '세미나실123',
            notice: '123ㅁㄴㄴㅁ4',
            intro: 'tgdㅁㄴㄴㅁsvcax',
            user: {
              id: 74,
              isAdmin: false,
              nickname: 'ttest',
              email: 'tester@t.com',
              password: '****',
              name: null,
              sex: null,
              profileImage: null,
              phoneNumber: null,
              businessNumber: null,
              businessName: null,
              businessAddress: null,
              accountNumber: null,
            },
          },
          user: {
            id: 74,
            isAdmin: false,
            nickname: 'ttest',
            email: 'tester@t.com',
            password: '****',
            name: null,
            sex: null,
            profileImage: null,
            phoneNumber: null,
            businessNumber: null,
            businessName: null,
            businessAddress: null,
            accountNumber: null,
          },
        },
      ],
    },
  };
}
