export class SpaceImageResExample {
  public readonly create = {
    status: 201,
    description: '새로운 space 이미지 등록 완료',
    success: true,
    data: {
      id: 1,
      imageUrl: 'https://s3.image.resizing.com',
      space: {
        type: '세미나실',
        address: '서울시 어쩌구',
        name: '좋은 세미나실',
        notice: '공지사항 어쩌구 저쩌구',
        intro: '넓고 깔끔',
        user: {
          id: 57,
          isAdmin: false,
          nickname: 'test2',
          email: 'test2@naver.com',
          password: '****',
          name: '김태훈',
          sex: null,
          profileImage: null,
          phoneNumber: null,
          businessNumber: null,
          businessName: null,
          businessAddress: null,
          accountNumber: null,
          reservations: [],
          spaces: [
            {
              id: 25,
              type: '스터디룸',
              address: '여기서 멀어요',
              name: '스터디룸 ㅋㅋ',
              notice: '공지사항 어쩌구 저쩌구',
              intro: '넓고 깔끔',
              hashtags: [],
            },
          ],
        },
        id: 26,
      },
    },
  };
  public readonly findAll = {
    status: 200,
    description: '전체 space 이미지(URL) 목록 조회 성공',
    success: true,
    data: [
      {
        type: '세미나실',
        address: '서울시 어쩌구',
        name: '좋은 세미나실',
        notice: '공지사항 어쩌구 저쩌구',
        intro: '넓고 깔끔',
        user: {
          id: 57,
          isAdmin: false,
          nickname: 'test2',
          email: 'test2@naver.com',
          password: '****',
          name: '김태훈',
          sex: null,
          profileImage: null,
          phoneNumber: null,
          businessNumber: null,
          businessName: null,
          businessAddress: null,
          accountNumber: null,
          reservations: [],
          spaces: [
            {
              id: 25,
              type: '스터디룸',
              address: '여기서 멀어요',
              name: '스터디룸 ㅋㅋ',
              notice: '공지사항 어쩌구 저쩌구',
              intro: '넓고 깔끔',
              hashtags: [],
            },
          ],
        },
        id: 26,
      },
      {
        id: 25,
        type: '스터디룸',
        address: '여기서 멀어요',
        name: '스터디룸 ㅋㅋ',
        notice: '공지사항 어쩌구 저쩌구',
        intro: '넓고 깔끔',
        user: {
          id: 57,
          isAdmin: false,
          nickname: 'test2',
          email: 'test2@naver.com',
          password: '****',
          name: '김태훈',
          sex: null,
          profileImage: null,
          phoneNumber: null,
          businessNumber: null,
          businessName: null,
          businessAddress: null,
          accountNumber: null,
          reservations: [],
          spaces: [
            {
              id: 26,
              type: '세미나실',
              address: '서울시 어쩌구',
              name: '좋은 세미나실',
              notice: '공지사항 어쩌구 저쩌구',
              intro: '넓고 깔끔',
            },
            {
              id: 25,
              type: '스터디룸',
              address: '여기서 멀어요',
              name: '스터디룸 ㅋㅋ',
              notice: '공지사항 어쩌구 저쩌구',
              intro: '넓고 깔끔',
            },
          ],
        },
        hashtags: [],
      },
    ],
  };
  public readonly findOne = {
    status: 200,
    success: true,
    description: 'Id로 spaceImage URL 조회 성공',
    data: {
      id: 1,
      imageUrl: 'https://s3.image.resizing.com',
      space: {
        type: '세미나실',
        address: '서울시 어쩌구',
        name: '좋은 세미나실',
        notice: '공지사항 어쩌구 저쩌구',
        intro: '넓고 깔끔',
        user: {
          id: 57,
          isAdmin: false,
          nickname: 'test2',
          email: 'test2@naver.com',
          password: '****',
          name: '김태훈',
          sex: null,
          profileImage: null,
          phoneNumber: null,
          businessNumber: null,
          businessName: null,
          businessAddress: null,
          accountNumber: null,
          reservations: [],
          spaces: [
            {
              id: 25,
              type: '스터디룸',
              address: '여기서 멀어요',
              name: '스터디룸 ㅋㅋ',
              notice: '공지사항 어쩌구 저쩌구',
              intro: '넓고 깔끔',
              hashtags: [],
            },
          ],
        },
        id: 26,
      },
    },
  };
  public readonly updateSpaceImage = {
    status: 201,
    description: 'SpaceImageId로 특정 Image(URL) 정보 수정',
    success: true,
    data: { affected: true },
  };

  public readonly removeSpaceImage = {
    status: 201,
    description: 'spaceImageId로 특정 spaceImage 삭제 성공',
    success: true,
  };
}
